### ISSUE TITLE
Bug - unnecessary bean creation by picocli

### ISSUE THREAD

**Issue by GuidoDechamps** [micronaut-projects/micronaut-picocli#28] opened 2020-04-25 14:13 UTC
In the class MicronautFactory, isn't this a bug?

   ```java
 @Override
    public <K> K create(Class<K> cls) throws Exception {
        return ctx.findOrInstantiateBean(cls).orElse(fallbackFactory.create(cls));
    }

```
The fallback factory will always be invoked. Which runs into trouble if I use constructor injection. Micronaut handles it fine, but then the fallback factory wants to create another, not necessary bean. But this fails since he wants the default constructor.

```

Caused by: java.lang.NoSuchMethodException: MyCommand.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4888)
	at io.micronaut.configuration.picocli.MicronautFactory.create(MicronautFactory.java:74)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4911)
```

**Comment by graemerocher** [comment] 2020-04-25 14:32
Wow it does look like one 🤦‍♂️

Fancy sending a PR?

**Comment by remkop** [comment] 2020-04-25 20:21
@GuidoDechamps What version are you using?

**Comment by remkop** [comment] 2020-04-25 20:28
This issue looks like a duplicate of https://github.com/micronaut-projects/micronaut-picocli/issues/7, which was fixed by PR https://github.com/micronaut-projects/micronaut-picocli/pull/8

@GuidoDechamps I suspect you are using micronaut 1.2.1, which is where that issue was introduced. The version prior to that (1.2.0) should not have this issue. @graemerocher may be able to tell you which later version of micronaut contains the fix.

**Comment by GuidoDechamps** [comment] 2020-04-26 08:47
> 
> 
> @GuidoDechamps What version are you using?

2.0.0.M2

**Comment by graemerocher** [comment] 2020-04-26 09:43
Will release 2.0.0 shortly

**Closed by graemerocher** 2020-04-26 09:43 UTC
Labels: bug

**Comment by graemerocher** [comment] 2020-04-26 10:20
Release in progress https://github.com/micronaut-projects/micronaut-picocli/runs/619538814?check_suite_focus=true

Note the Maven group changed to `io.micronaut.picocli` with Micronaut 1.3.x minimum version. Thanks for the feedback
